<template>
	<div class="col-span-full grid grid-cols-12 relative text-white mt-20 overflow-hidden">
		<img src="@/assets/images/wallpaper-dark.webp" alt="dark-wallpaper"
		     class="absolute top-0 left-0 z-[-1]">
		<container>
			<div class="flex items-center justify-center my-24 mt-64">
				<h2 class="text-5xl font-bold">
					Scaling Decentralized Music
					<br>
					Across Protocols & Borders
				</h2>
			</div>

			<div class="grid grid-cols-2 mt-48 mb-32">
				<div class="border-t py-6 pr-12">
					<h3 class="text-2xl font-semibold mb-16">
						Our vision
					</h3>
					<p class="text-lg text-justify">
						We are bringing the old fashioned music industry to the 21st century connecting it to
						the
						awesome world of blockchain technology and decentralization.
					</p>
					<p class="text-lg text-justify mt-6">
						Let's create the biggest music blockchain ecosystem!
					</p>
					<p class="text-lg text-justify mt-6">
						Join us and spread this new love!
					</p>
				</div>
				<div class="flex items-center justify-center">
					<img src="@/assets/images/boubles.webp" alt="boubles">
				</div>
			</div>

			<div class="grid grid-cols-2 mt-48 mb-32">
				<div class="flex items-center justify-center">
					<img src="@/assets/images/boubles-2.webp" alt="boubles">
				</div>
				<div class="border-t py-6 pr-12">
					<h3 class="text-2xl font-semibold mb-16">
						The problems of the music industry
					</h3>
					<p class="text-lg text-justify">
						Income inequality: Top 1% of the artists earns 77% of the all recorded music income.
					</p>
					<p class="text-lg text-justify mt-6">
						Underpaid artists: Most artists earn just between 6% and 18% of the revenue generated by
						their creations.
					</p>
					<p class="text-lg text-justify mt-6">
						Greedy middleman: 85% to 90% of global music industry revenue goes to third parties.
					</p>
					<p class="text-lg text-justify mt-6">
						Outdated business model: The music industry hasn't yet caught up to the digital
						revolution.
					</p>
				</div>
			</div>

			<div class="grid grid-cols-2 mt-48 mb-32">
				<div class="border-t py-6 pr-12">
					<h3 class="text-2xl font-semibold mb-16">
						Our goal
					</h3>
					<p class="text-lg text-justify">
						We think that music is a must in everyone's life and that everyone should have the
						possibility to get a living out of their talent.
					</p>
					<p class="text-lg text-justify mt-6">
						Melodity aims to change how independent musicians earn revenue from their creations
						giving them the freedom to monetize while increasing their visibility in the musical
						scene.
					</p>
				</div>
				<div class="flex items-center justify-center">
					<img src="@/assets/images/boubles-3.webp" alt="boubles">
				</div>
			</div>

			<a :href="buyMeldUrl" target="_blank" rel="noopener"
			   class="text-white text-center font-bold rounded-full w-full bg-gradient-to-tr from-[#f56ec6] to-[#e94ac8]
							via-[#f56ec6] bg-left flex items-center justify-center p-4 w-1/3 mx-auto my-48">
				Buy MELD
			</a>

			<div class="text-center mt-32 mb-96">
				<h3 class="text-2xl mb-8">
					MELD are available on
				</h3>
				<div class="grid grid-cols-5">
					<a v-for="(elem, id) of randomListings" :key="id" :href="elem.url" target="_blank"
					   rel="noopener"
					   class="flex items-center justify-center p-8">
						<img :src="elem.logo" :alt="elem.name">
					</a>
				</div>
			</div>
		</container>
	</div>
</template>

<script>
import Container from "@/components/Container";
export default {
	name: "AboutExtended",
	components: {Container},
	props: {
		randomListings: {
			type: Array,
			required: true,
		},
		buyMeldUrl: {
			type: String,
			required: true,
		},
	},
}
</script>

<style scoped>

</style>