<template>
	<div class="col-span-full grid grid-cols-12 relative text-white mt-20 overflow-hidden">
		<img src="@/assets/images/wallpaper-dark.webp" alt="dark-wallpaper"
		     class="absolute top-0 left-0 z-[-1]">
		<img src="@/assets/images/wallpaper-dark.webp" alt="dark-wallpaper"
		     class="absolute top-full xl:-translate-y-1/4 lg:-translate-y-3/4 translate-y-[-225%] left-0 z-[-1] 2xl:hidden block">
		<img src="@/assets/images/wallpaper-dark.webp" alt="dark-wallpaper"
		     class="absolute top-full xl:-translate-y-1/4 lg:-translate-y-3/4 translate-y-[-150%] left-0 z-[-1] lg:hidden block">
		<img src="@/assets/images/wallpaper-dark.webp" alt="dark-wallpaper"
		     class="absolute top-full xl:-translate-y-1/4 lg:-translate-y-3/4 -translate-y-2/3 left-0 z-[-1] lg:hidden block">
		<container>
			<div class="flex items-center justify-center lg:my-24 mt-48">
				<h2 class="lg:text-5xl text-4xl font-semibold font-raleway">
					Scaling Decentralized Music
					<br>
					Across Protocols & Borders
				</h2>
			</div>

			<div class="grid lg:grid-cols-2 grid-cols-1 mt-48 mb-32 lg:gap-12">
				<div class="py-6 pr-12 font-raleway font-light">
					<h3 class="text-2xl font-semibold mb-16 font-semibold font-raleway relative lg:text-left text-center
						lg:after:hidden after:content-[''] after:absolute after:-translate-x-1/2 after:left-1/2
						after:-bottom-4 after:h-1 after:w-16 after:rounded-full after:bg-[#783A8A]">
						Our vision
					</h3>
					<p class="lg:text-lg text-xl text-center ">
						We are bringing the old fashioned music industry to the 21st century connecting it to
						the
						awesome world of blockchain technology and decentralization.
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Let's create the biggest music blockchain ecosystem!
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Join us and spread this new love!
					</p>
				</div>
				<div class="flex items-center justify-end pl-4 lg:order-last order-first">
					<img src="@/assets/images/boubles.webp" alt="boubles">
				</div>
			</div>

			<div class="grid lg:grid-cols-2 grid-cols-1 mt-48 mb-32 lg:gap-12">
				<div class="flex items-center justify-start pr-12">
					<img src="@/assets/images/boubles-2.webp" alt="boubles">
				</div>
				<div class="py-6 pr-12 font-raleway font-light">
					<h3 class="text-2xl font-semibold mb-16 font-semibold font-raleway relative lg:text-left text-center
						lg:after:hidden after:content-[''] after:absolute after:-translate-x-1/2 after:left-1/2
						after:-bottom-4 after:h-1 after:w-16 after:rounded-full after:bg-[#783A8A]">
						The problems of the music industry
					</h3>
					<p class="lg:text-lg text-xl text-center ">
						Income inequality: Top 1% of the artists earns 77% of the all recorded music income.
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Underpaid artists: Most artists earn just between 6% and 18% of the revenue generated by
						their creations.
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Greedy middleman: 85% to 90% of global music industry revenue goes to third parties.
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Outdated business model: The music industry hasn't yet caught up to the digital
						revolution.
					</p>
				</div>
			</div>

			<div class="grid lg:grid-cols-2 grid-cols-1 mt-48 mb-32 lg:gap-12">
				<div class="py-6 pr-12 font-raleway font-light">
					<h3 class="text-2xl font-semibold mb-16 font-semibold font-raleway relative lg:text-left text-center
						lg:after:hidden after:content-[''] after:absolute after:-translate-x-1/2 after:left-1/2
						after:-bottom-4 after:h-1 after:w-16 after:rounded-full after:bg-[#783A8A]">
						Our goal
					</h3>
					<p class="lg:text-lg text-xl text-center ">
						We think that music is a must in everyone's life and that everyone should have the
						possibility to get a living out of their talent.
					</p>
					<p class="lg:text-lg text-xl text-center mt-6">
						Melodity aims to change how independent musicians earn revenue from their creations
						giving them the freedom to monetize while increasing their visibility in the musical
						scene.
					</p>
				</div>
				<div class="flex items-center justify-end pl-8 lg:order-last order-first">
					<img src="@/assets/images/boubles-3.webp" alt="boubles">
				</div>
			</div>

			<a :href="buyMeldUrl" id="buy-meld"
			   class="text-white text-center font-bold rounded-full w-full bg-gradient-to-tr from-[#f56ec6] to-[#e94ac8]
							via-[#f56ec6] bg-left flex items-center justify-center p-4 w-1/3 mx-auto lg:my-48 my-12
						font-mulish font-medium">
				Buy MELD
			</a>

			<div class="text-center mt-32 mb-96">
				<h3 class="text-2xl mb-8 font-semibold font-raleway">
					MELD are available on
				</h3>
				<div class="grid lg:grid-cols-5 grid-cols-2 gap-8">
					<a v-for="(elem, id) of randomListings" :key="id" :href="elem.url" target="_blank"
					   rel="noopener"
					   class="flex items-center justify-center p-8">
						<img :src="elem.logo" :alt="elem.name">
					</a>
				</div>
			</div>
		</container>
	</div>
</template>

<script>
import Container from "@/components/Container";
export default {
	name: "AboutExtended",
	components: {Container},
	props: {
		randomListings: {
			type: Array,
			required: true,
		},
		buyMeldUrl: {
			type: String,
			required: true,
		},
	},
}
</script>

<style scoped>

</style>